name: Loki Task

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and start containers for a services
      run: docker compose up -d

    - name: Wait for Grafana
      run: |
        until curl -s -o /dev/null -w "%{http_code}" http://localhost:9090 | grep 200; do
          echo "Waiting for Grafana..."
          sleep 5
        done

    - name: Test containers functionality
      uses: cypress-io/github-action@v6
      env:
        CYPRESS_BASE_URL: http://localhost:8080
        CYPRESS_GRAFANA_URL: http://localhost:9090
      with:
        working-directory: ./.github/tests
